-- ============================================================
-- dim_station — dimensi stasiun
--
-- Dimensi stasiun berisi DUA kolom id, karena kedua fact table memakai gaya
-- id yang berbeda dan tidak saling mengenal:
--
--   station_id       -> id legacy dari riwayat trip ('5343.10', 'JC116')
--   gbfs_station_id  -> id feed GBFS (UUID / snowflake)
--
-- Join langsung antara riwayat trip dan feed GBFS menghasilkan 0 baris cocok;
-- penghubungnya kolom `short_name` pada GBFS, yang justru berisi id legacy.
-- Penjelasan lengkap ada di int_station_id_bridge, tempat definisinya berada.
--
-- Catatan pengembangan:
--
-- - Model ini 1:1 dengan int_station_id_bridge. Isinya sengaja tidak
--   dihitung ulang di sini supaya int_station_risk_calculation (intermediate)
--   dapat memakai pemetaan yang sama tanpa membaca marts/core.
--
-- - SELECT * memang disengaja: menyalin daftar kolom berarti dua tempat yang
--   bisa menyimpang. Kolom baru di bridge otomatis ikut ke sini.
-- ============================================================

SELECT * FROM {{ ref('int_station_id_bridge') }}
